Repository greenplum-db/plcontainer, pull requests merged in 2018-05, with the labels that each got.

#353 Don't throw exception for runtime-show when there is no runtime in xml
  management/bin/plcontainer
  tests/expected/test_utility.out
Labels: unscheduled

#360 Remove elog in cleanup process.
  src/common/comm_utils.h
  src/plc_docker_api.c
Labels: accepted

#362 Add datasciencebundle regression tests to plcontainer
  tests/Makefile
  tests/expected/python_import_module.out
  tests/expected/r_import_library.out
  tests/pl_schedule
  tests/sql/python_import_module.sql
  tests/sql/r_import_library.sql
Labels: unscheduled

#363 Fix include files due to GPDB upgrade to PG9.1.
  src/containers.c
  tests/expected/test_utility.out
Labels: unscheduled

#364 Using separate answer files.
  tests/expected/python_import_module.out
  tests/expected/r_import_library.out
  tests/expected/test_utility.out
Labels: unscheduled

#365 Update README.
  README.md
Labels: unscheduled

#361 make plcontainer PostgreSQL compatible initial version
  Makefile
  README.md
  README_PG.md
  management/bin/plcontainer
  management/sql/plcontainer_gp--1.0.0.sql
  management/sql/plcontainer_install.sql.in
  management/sql/plcontainer_pg--1.0.0.sql
  src/containers.c
  src/message_fns.c
  src/plc_configuration.c
  src/plc_docker_api.c
  src/plc_typeio.c
  src/plcontainer.c
  src/sqlhandler.c
  tests/Makefile
  tests/drop_pg.sql
  tests/exception_pg.sql
  tests/expected/drop_pg.out
  tests/expected/exception_pg.out
  tests/expected/runtimeid_declaration_pg.out
  tests/expected/schema_pg.out
  tests/expected/spi_python_pg.out
  tests/expected/spi_r_pg.out
  tests/expected/subtransaction_python_pg.out
  tests/expected/test_python_error_pg.out
  tests/expected/test_python_pg.out
  tests/expected/test_r_error_pg.out
  tests/expected/test_r_pg.out
  tests/expected/uda_python_pg.out
  tests/expected/uda_r_pg.out
  tests/pl_schedule_pg
  tests/runtimeid_declaration_pg.sql
  tests/schema_pg.sql
  tests/spi_python_pg.sql
  tests/spi_r_pg.sql
  tests/sql/drop_pg.sql
  tests/sql/exception_pg.sql
  tests/sql/runtimeid_declaration_pg.sql
  tests/sql/schema_pg.sql
  tests/sql/spi_python_pg.sql
  tests/sql/spi_r_pg.sql
  tests/sql/subtransaction_python_pg.sql
  tests/sql/test_python_error_pg.sql
  tests/sql/test_python_pg.sql
  tests/sql/test_r_error_pg.sql
  tests/sql/test_r_pg.sql
  tests/sql/uda_python_pg.sql
  tests/sql/uda_r_pg.sql
  tests/subtransaction_python_pg.sql
  tests/test_python_error_pg.sql
  tests/test_python_pg.sql
  tests/test_r_error_pg.sql
  tests/test_r_pg.sql
  tests/uda_python_pg.sql
  tests/uda_r_pg.sql
Labels: in progress

#373 Support User Access Control White List For Selected Runtimes
  management/bin/plcontainer
  src/containers.c
  src/plc_configuration.c
  src/plc_configuration.h
  src/plcontainer.c
  tests/pl_schedule
Labels: in progress

#375 Add missing regression file
  tests/expected/user_control.out
  tests/sql/user_control.sql
Labels: unscheduled

#379 Change the GPDB installation folder for CCP
  concourse/scripts/docker_build_image.sh
Labels: unscheduled
